name: python_for_geosciences
channels:
  - conda-forge
dependencies:
  - python=3.7
  - netcdf4=1.2.9
  - pandas=1.0.3
  - scipy
  - requests
  - matplotlib
  - basemap
  - cartopy
  - pydap
  - xarray
